### PR TITLE
Importing Projects

### PR DESCRIPTION
**Pull request by will-v-pi**
Add importing of projects to pico_project.py - works for most examples folders, and will sometimes work for existing projects

Uses -conv to convert an existing project, and -exam to convert an examples folder

Also remove tkinter, as that configuration method is not used by the extension

### CODE REVIEW

**Review by paulober — APPROVED** [review]
Thanks for the help. Removing tkinter was always on my TODO.
And the data loss risk you mentioned does only count for the CMakeLists.txt?

**Comment by will-v-pi** [comment]
It should only be CMakeLists.txt, and also the files in the .vscode folder will be overwritten entirely

**Comment by paulober** [comment]
@will-v-pi How would you want the import process to work?
To configure all the vscode settings the extension must at least ask for a sdk version, then for advance options => YES => cmake, ninja and toolchain version.

But since we overwrite CMakeListst.txt we need to ask all options that are required for a new project with the only difference being no samples are generated for libraries that you select and instead of a project root and name you now only have to select a folder. So using the "new project web view" but with no name input would be the best solution here. 
What do you think?

**Comment by will-v-pi** [comment]
Yeah, I agree - we should use the webview, but with just the Basic Settings (and advanced options) section, so no Features/Stdio support etc - the expectation would be when importing a project you already have a correct CMakeLists,txt file setup with all the libraries etc, it just needs the "DO NEVER EDIT THE NEXT LINES..." section added to the file, and all the vscode stuff. The rest of the CMakeLists.txt file will remain untouched

As for how to open the webview, I think a popup when opening a project that isn't configured with a button, and also a button in the quick actions sidebar.

For importing examples into the project, I think it would be good to have the same webview as importing existing projects, but with a search bar instead of project name. We should probably also make a json file listing all the examples and their paths (as they're at different depths in the examples repo, and they may not all work seamlessly, so I'll do that manually and add it to data), so the search can just search that, and then sparse-checkout can checkout only the required directories.

I've also had a play with the sparse checkout, and I think we should be fine to just do:
```
git clone --filter=blob:none --sparse https://github.com/raspberrypi/pico-examples.git
git sparse-checkout set --cone
```
the first time anyone wants to open an example (init is now deprecated, and set doesn't require a path, so these commands should work with all git >=2.35 - MacOS and RPiOS are 2.39 so should be fine), and then
```
git sparse-checkout add blink
or
git sparse-checkout add pico_w/wifi/blink
etc
```
using the paths from the json, to get the files for specific examples, then just copy that directory to wherever the user inputs in the webview.

Does that all sound good?

**Comment by paulober** [comment]
Sounds good.

Tow questions:
> using the paths from the json, to get the files for specific examples, then just copy that directory to wherever the user inputs in the webview.

Which json do you mean?

So for the examples you mean I should show a list, the user selects one. I sparse-checkout then I copy it to the project directory (I ask the user about this after selecting the example). Then I call the pico project generator only with `-exam` and the path to the new folder containing the example?

**Comment by will-v-pi** [comment]
I'll make an examples.json file in data, which can then be downloaded from github pages by the extension, which contains that info - I'll push a small one with a few examples, and then test the rest and push more as I check they actually work with the import script

For examples, maybe a search bar with a dropdown, instead of a list? You can just have that in the Name field of the webview, and then they select the directory using the Location field of the webview, and then only when they click create you:
- Sparse-checkout the required folder (if it isn't already) and copy it to the specified location (eg I choose /home/me/code/ and want blink, so copy it to /home/me/code/blink)
- Call pico project generator as per usual, with the location and name set as if you're creating a new project along with cmake paths etc, just with the added `-exam` argument
- Should just work, and you can open the folder once generated

**Comment by will-v-pi** [comment]
So like this, where path is the directory to copy, and name is what you pass to pico_project.py as the project name - the key is what the user will search for
```
{
  "blink": {
    "path": "blink",
    "name": "blink"
  },
  "hello_serial": {
    "path": "hello_world/serial",
    "name": "serial"
  },
  "picow_blink": {
    "path": "pico_w/wifi/blink",
    "name": "blink"
  }
}
```
Does that sound good?

**Pull request merged**
